# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b7ed40a2f059df66c22c9ea66112c94580f370e3dcc79fac2f4c8df8e41453d2b1e1b9d81fdd74442ec72ddeb1944f04b9273a3e8aa9926f13a6ea3cd263ad0f

test:
  secret_key_base: e6f8b329a5c0c2b00e55dbba8a34bfd4e8c06086c61763c9ce87ebbf3b7ce71ae795ab0b11ba83b3877bcbec3ee922ee46f37d8df772532e08d155ff3b6f200c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
